name: CTest Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: CTest build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: System Information
        run: gcc --version && g++ --version

      - name: gcc make
        run: make

      - name: clean
        run: make clean

      - name: g++ make
        run: make CC=g++

  test:
    name: CTest tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # compile
      - name: gcc make
        run: make TYPE=test
      - name: gcc tests
        run: make test

      # run
      - name: test
        run: bash test/run.sh

      - name: coverage
        run: make coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          flags: unittests
          name: build
          fail_ci_if_error: true
          # verbose: true

      - name: clear
        run: make clear

      - name: g++ tests
        run: make CC=g++ test
      - name: g++ run tests
        run: bash test/run.sh
