name: CTest Production Integration

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: CTest production build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: gcc make
        run: make TYPE=production

      - name: Archive Shared Library
        uses: actions/upload-artifact@v2
        with:
          name: ctest-lib
          path: ./bin/libctest.so
          retention-days: 1

      - name: clean
        run: make clean

      - name: g++ make
        run: make TYPE=production CC=g++
  
  test:
    name: CTest tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Shared Library
        uses: actions/download-artifact@v2
        with:
          name: ctest-lib
          path: ./bin

      - name: gcc tests
        run: make test
      - name: gcc run tests
        run: bash test/run.sh

      - name: clear
        run: make clear

      - name: g++ tests
        run: make CC=g++ test
      - name: g++ run tests
        run: bash test/run.sh
