name: Test

on:
  push:
    branches:
      - 'work'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version file
        id: get_version
        run: echo "::set-output name=version::$(cat version.txt)"

      - name: Display version
        run: echo ${{ steps.get_version.outputs.version }}

      - name: Read changelog
        id: get_changes
        run: |
          changes=$(cat CHANGELOG.md)
          changes="${changes//'%'/'%25'}"
          changes="${changes//$'\n'/'%0A'}"
          changes="${changes//$'\r'/'%0D'}"
          echo "::set-output name=changes::$changes"

      # - name: Display changelog
      #   run: echo ${{ steps.get_changes.outputs.changes }}